language: generic
# language: rust

env:
  global
    - ZOLA_RELEASES=https://github.com/getzola/zola/releases/download
    - ZOLA_V=v0.5.1
    - ARCH=x86_64-unknown-linux-gnu

install:
  # - export PATH="$PATH:$HOME/.local/bin"
  # - >
  #   curl -LSfs https://japaric.github.io/trust/install.sh | \
  #       sh -s -- \
  #          --force \
  #          --git getzola/zola \
  #          --tag v0.5.1 \
  #          --target x86_64-unknown-linux-gnu \
  #          --to ~/.local/bin
  # - curl https://github.com/getzola/zola/releases/download/v0.5.1/zola-v0.5.1-x86_64-unknown-linux-gnu.tar.gz
  - curl -L ${ZOLA_RELEASES}/${ZOLA_V}/zola-${ZOLA_V}-${ARCH}.tar.gz | tar -xz
  - ./zola --version

script:
  - ./zola build

notifications:
  email:
    on_success: never

deploy:
  provider: pages
  local_dir: public
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: scripts  # TODO: change to master
