# language: generic
language: rust

before_install: set -e

install:
  - export PATH="$PATH:$HOME/.local/bin"
  - echo 123
  - mkdir -p ~/.local/bin
  - >
    curl -LSfs https://japaric.github.io/trust/install.sh | \
        sh -s -- \
           --force \
           --git getzola/zola \
           --tag v0.5.1 \
           --target x86_64-unknown-linux-gnu \
           --to ~/.local/bin
  # - bash ci/install.sh
  - zola --version

script:
  - zola build
  # - bash ci/script.sh

after_success:
  - ls
  - >
    # if [ $TRAVIS_BRANCH = master ] && [ $TRAVIS_PULL_REQUEST = false ]; then
    if [ $TRAVIS_BRANCH = scripts ] && [ $TRAVIS_PULL_REQUEST = false ]; then
      curl -Ls https://github.com/davisp/ghp-import/archive/master.tar.gz | tar --strip-components 1 -C ghp-import -xz

      ./ghp-import/ghp_import.py public

      set +x
      git push -fq https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git gh-pages && echo OK
    fi
  # - bash ci/after-success.sh

after_script: set +e

# branches:
#   only:
#     - master
#     - staging
#     - trying

notifications:
  email:
    on_success: never
