# language: generic
language: rust

before_install: set -e

install:
  # - pip install --user ghp-import
  - export PATH="$PATH:$HOME/.local/bin"
  - echo 123
  - mkdir -p ~/.local/bin
  - >
    curl -LSfs https://japaric.github.io/trust/install.sh | \
        sh -s -- \
           --force \
           --git getzola/zola \
           --tag v0.5.1 \
           --target x86_64-unknown-linux-gnu \
           --to ~/.local/bin
  - zola --version

script:
  - zola build
      
# if [ $TRAVIS_BRANCH = master ] && [ $TRAVIS_PULL_REQUEST = false ]; then

after_success:
  - ls
  - |
    if [ $TRAVIS_BRANCH = scripts ] && [ $TRAVIS_PULL_REQUEST = false ]; then
      ghp-import public
      git push -fq https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git gh-pages && echo OK
    fi
  - ls

after_script: set +e

# branches:
#   only:
#     - master
#     - staging
#     - trying

notifications:
  email:
    on_success: never

deploy:
  provider: pages
  local_dir: public
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: scripts
