[[crates]]
name = "benzene-2d"
source = "crates"

[[crates]]
name = "beryllium"
source = "crates"

[[crates]]
name = "blit"
source = "crates"

[[crates]]
name = "elmesque"
source = "crates"

[[crates]]
name = "fermium"
source = "crates"

[[crates]]
name = "hex2d"
source = "crates"

[[crates]]
name = "image"
source = "crates"

[[crates]]
name = "lyon"
source = "crates"

[[crates]]
name = "nuklear-rust"
source = "crates"

[[crates]]
name = "piston2d-graphics"
source = "crates"

[[crates]]
name = "rusttype"
source = "crates"

[[crates]]
name = "sdl2"
source = "crates"

[[crates]]
name = "sfml"
source = "crates"

