name: Rust

on: [push]

# TODO: Make sure it works only on commits to master branch!

jobs:
  test_Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: zola install & build
      env:
        BASE_URL: https://github.com/getzola/zola/releases/download
        VERS: v0.5.1
        ARCH: x86_64-unknown-linux-gnu
      run: |
        curl -L ${BASE_URL}/${VERS}/zola-${VERS}-${ARCH}.tar.gz | tar -xz
        ./zola --version
        ./zola build
    - name: Test Test 3
      run: pwd
