name: Zola

on:
  push:
    branches:
      - master

jobs:
  zola:
    runs-on: ubuntu-latest
    env:
      BASE_URL: https://github.com/getzola/zola/releases/download
      VERS: v0.5.1
      ARCH: x86_64-unknown-linux-gnu
    steps:
    - uses: actions/checkout@v1
    - name: Install Zola
      run: curl -L ${BASE_URL}/${VERS}/zola-${VERS}-${ARCH}.tar.gz | tar -xz
    - run: ./zola --version
    - run: ./zola build
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v1
      with:
        build_dir: public
      env:
        # https://github.com/marketplace/actions/github-pages#warning-limitation
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
